### ISSUE TITLE
Edit cart

### ISSUE THREAD

**Issue by BhavanaSJain** [softkoash-ashishjain/brunchery_v1#119]
![image](https://user-images.githubusercontent.com/8385702/44962470-cc95c280-af3e-11e8-87f8-81072f645ba0.png)

**Comment by softkoash-ashishjain** [comment]
That circle colour should be brunchery colour

**Comment by softventure** [comment]
If you have not merged the fixes to mobile code, please do not push them now. This item stands as duplicate to issue #63 and Shailesh fixed it correctly. I have copied his fix.
