### ISSUE TITLE
Sold out feature

### ISSUE THREAD

**Issue by softkoash-ashishjain** [softkoash-ashishjain/brunchery_v1#15]
Steps:
1. Go to merchant page.
2. Select food item.
3. Tick item not available for any one item.
4. Refresh the main website that shows the food item of that merchant.

Expected Result: It should show 'Sold out' label in place of plus button.

Error: It shows plus button, and when we click on it, it shows error message: "Item not available".

**Comment by softventure** [comment]
Fixed and pudhe to github
