### ISSUE TITLE
Food item flitering 

### ISSUE THREAD

**Issue by softkoash-ashishjain** [softkoash-ashishjain/brunchery_v1#16]
Error: Open food item page. Click on food catagories, list is not filtered accordingly.

**Comment by softventure** [comment]
I tried to reproduce this issue but unable to. The filters on the restaurant listing page seem to be working correctly. I tested both the delivery type and cuisine filters.

**Comment by BhavanaSJain** [comment]
The list in food menu, is not filtered.

**Comment by BhavanaSJain** [comment]
Steps to reproduce are:
1. Select restaurant mc Donald's.
2. Select breakfast, now list is not filtered

**Comment by BhavanaSJain** [comment]
Steps to reproduce are:
1. Select restaurant mc Donald's.
2. Select breakfast, now list is not filtered

**Comment by softventure** [comment]
Yes, this is known issue. This is fixed in mobile app. need to apply similar fix to web.

**Comment by softventure** [comment]
Fixed and available on softkoashsolution.in
