### ISSUE TITLE
Error while we do payment

### ISSUE THREAD

**Issue by softkoash-ashishjain** [softkoash-ashishjain/brunchery_v1#17]
Steps:
Normally click on Proceed to payment button, you get error message. Screen shot of this issue, I have sent you on Whats app.

**Comment by softventure** [comment]
I tried to reproduce but unable to. I can put the filters on restaurant listing page and search results are working based on selected filters.

**Comment by softventure** [comment]
This looks to be issue with the date fields in mysql having strict mode. This is an open issue with Karenderia.

**Comment by softventure** [comment]
This has been fixed. There was delivery date which was null. Fixed to set it to current date for now. We anyways do not allow delivery so we should be fine.
