### ISSUE TITLE
Restaurant image correction

### ISSUE THREAD

**Issue by softkoash-ashishjain** [softkoash-ashishjain/brunchery_v1#18]
1. In PDF restaurant image, should have timings.
2. There is opening and closing time in image below.

**Comment by softventure** [comment]
In merchant admin page, user should be able to set open close timings. Based on this information, the timings are set in front.

**Comment by Harsha18** [comment]
Timings are not visible even after setting timings from merchant admin page

**Comment by softventure** [comment]
This should be fixed now.

**Comment by BhavanaSJain** [comment]
In mobile app, timings and discount are not displayed properly. Like they should right aligned in a single line.

**Comment by softventure** [comment]
Please open a separate ticket for prep timings and cups discount. This issue talks about open/close timings of restaurant.
