### ISSUE TITLE
Sold Out button

### ISSUE THREAD

**Issue by BhavanaSJain** [softkoash-ashishjain/brunchery_v1#28]
It should be right aligned as shown in pdf.

**Comment by softventure** [comment]
It is right aligned. What is the issue?

**Comment by softventure** [comment]
On the web, it needs to be on the extreme right side.

**Comment by softventure** [comment]
![image](https://user-images.githubusercontent.com/19835091/44300586-179cbc80-a327-11e8-8f1d-b1b34e04b42c.png)
@sawantsh Looks like when the sold out button has a margin on the right side. Please take a look.
