### ISSUE TITLE
Login/Signup button to use the extra space and be bigger in size

### ISSUE THREAD

**Issue by BhavanaSJain** [softkoash-ashishjain/brunchery_v1#33]
Headings and options should be as per pdf.

**Comment by softventure** [comment]
The PDF did not have the logout button. We had to add that on the top as part of heading. We now have centered the "Profile" title similar to other pages.

**Comment by BhavanaSJain** [comment]
Login/ sign up button should all the extra space

**Comment by sawantsh** [comment]
Do they want something like this

![image](https://user-images.githubusercontent.com/18049665/45039329-0b339600-b081-11e8-9cac-e701a3d12d21.png)

**Comment by softventure** [comment]
This looks ugly. @BhavanaSJain Please take client feedback before we change it.
