### ISSUE TITLE
Order details TRN type

### ISSUE THREAD

**Issue by softkoash-ashishjain** [softkoash-ashishjain/brunchery_v1#40]
While placing order
- Dash In / Dash Out options
- Choose anything
- Place the order
- In order details TRN type its always displaying as "dashin"

**Comment by softventure** [comment]
![image](https://user-images.githubusercontent.com/19835091/44297721-d63ee980-a2f3-11e8-989a-7ab2e44e8ca7.png)

**Comment by softventure** [comment]
This issue was coming up in Web and not mobile. Have fixed it. Will be part of next deployment.

**Comment by BhavanaSJain** [comment]
In mobile app, receipt like this is not shown.

**Comment by softventure** [comment]
Please create separate ticket for mobile app. The issue here talks about issue with TRN type field, not about look and feel about receipt in mobile vs web.
