### ISSUE TITLE
Food menu page

### ISSUE THREAD

**Issue by BhavanaSJain** [softkoash-ashishjain/brunchery_v1#48]
Need to remove size of food.

**Comment by softventure** [comment]
This piece is Karenderia functionality. We need to remove the size from the admin too. Can you confirm they don't need the size for food item the way Karenderia supports?

**Comment by BhavanaSJain** [comment]
It should not show the size like small, prize should be shown of size small and while doing payment user will decide different sizes.

**Comment by softventure** [comment]
Fixed and deployed.
