### ISSUE TITLE
Purchasing food item

### ISSUE THREAD

**Issue by BhavanaSJain** [softkoash-ashishjain/brunchery_v1#57]
Steps to reproduce error:
1. Without login add some item to cart.
2. Tap on checkout button.
3. Login page appears.
4. Add credentials and login.

Error: After login main dashboard page appears.

Expected result: It should go back to checkout page.

**Comment by softventure** [comment]
This issue is in mobile app. This fix is made in the Rapindinho project. Please copy the fix to Brunchery V1.

**Comment by Harsha18** [comment]
done.
