### ISSUE TITLE
Facebook login not there

### ISSUE THREAD

**Issue by BhavanaSJain** [softkoash-ashishjain/brunchery_v1#58]
In login page there is Facebook login.

**Comment by softventure** [comment]
Harsha is looking into it. It would be configuration on the admin side. Karenderia already has code in place to integrate with Facebook and Google OAuth.

**Comment by softventure** [comment]
Harsha, Any update here or should I look info this too?

**Comment by Harsha18** [comment]
Facebook login working on my localhost, not on softkoashsolution.in.
It's a HTTPS Enforce issue.
 https://stackoverflow.com/questions/49400199/why-enforce-https-is-forcefully-set-as-yes/49778678#49778678

**Comment by softventure** [comment]
Thanks @Harsha18. So, the request to facebook oauth needs to be from https site. We should mark this issue as fixed in that case. It is a pre-requisite step which the customer needs to follow.
