### ISSUE TITLE
Add items in cart bar in app

### ISSUE THREAD

**Issue by softkoash-ashishjain** [softkoash-ashishjain/brunchery_v1#63]
It should just look like in website.

**Comment by BhavanaSJain** [comment]
![image](https://user-images.githubusercontent.com/8385702/44715925-a4d5d300-aad6-11e8-83f8-251e3f13faf6.png)
1 written is in red colour circle, whereas in website, it is perfect.

**Comment by softventure** [comment]
@sawantsh Please take a look.

**Comment by sawantsh** [comment]
committed fix
