### ISSUE TITLE
Cart item addition

### ISSUE THREAD

**Issue by BhavanaSJain** [softkoash-ashishjain/brunchery_v1#65]
As item is added to cart, there is animation in Peer food, we need to copy that.

**Comment by softventure** [comment]
In peerfood, when item is added to cart, lot of options are displayed. Are you referring to those? For the animation, we have used the bounce animation on the cart icon on the bottom left. Is that not enough? Please provide the video of animation you want.

**Comment by BhavanaSJain** [comment]
I have sent you video on whats app

**Comment by softventure** [comment]
I believe there is another duplicate item https://github.com/softkoash-ashishjain/brunchery_v1/issues/76. Please close one of them.
