### ISSUE TITLE
Splash screen(Same issue in both project)

### ISSUE THREAD

**Issue by BhavanaSJain** [softkoash-ashishjain/brunchery_v1#66]
This should not happen in splash screen loading.
![image](https://user-images.githubusercontent.com/8385702/44658631-19e5d180-aa1f-11e8-862a-245769112dc2.png)

**Comment by BhavanaSJain** [comment]
Loading sign should be something like this:

![image](https://user-images.githubusercontent.com/8385702/44658680-46015280-aa1f-11e8-8ac8-2780432c9edb.png)

**Comment by sawantsh** [comment]
Loader update are pushed
