### ISSUE TITLE
Search Result images

### ISSUE THREAD

**Issue by BhavanaSJain** [softkoash-ashishjain/brunchery_v1#71]
Images need to be slightly longer than they are now. They are a little thin at the moment.

**Comment by softventure** [comment]
Which images are you referring to? Please provide screenshot.

**Comment by BhavanaSJain** [comment]
![image](https://user-images.githubusercontent.com/8385702/44865722-b66ad680-aca0-11e8-87a0-8bae74a164a2.png)

These images are search result of market yard pune.

**Comment by softventure** [comment]
@sawantsh Please take a look.

**Comment by softventure** [comment]
@BhavanaSJain Please specify the size required in both web and mobile.

**Comment by sawantsh** [comment]
Image height is icreased from 180px to 220px. Also to clarify, image size is not chnaging or (being changed) for search results as mentioned in comments above
