### ISSUE TITLE
Search result

### ISSUE THREAD

**Issue by BhavanaSJain** [softkoash-ashishjain/brunchery_v1#74]
When the customer selects their address from the drop down in the search bar, the site should
automatically load.

Steps:
1. Type address in search bar.
2. Select address from drop down menu.
3. Search Results load for
that address

**Comment by softventure** [comment]
In that case, we do not need the search icon. Please clarify.

**Comment by BhavanaSJain** [comment]
Expected result: when user select search option from drop down menu, search result should be shown.

Error: user selects from drop down menu, and clicks on search button to get results.
