### ISSUE TITLE
Menu UX exactly like peer food

### ISSUE THREAD

**Issue by BhavanaSJain** [softkoash-ashishjain/brunchery_v1#76]
1. When you select an item in Peerfood the little plus sign jumps from the food item and lands in the cart
2. Peerfood gives customer immediate option to change the quantity of the item from the menu by clicking “+”
or “-“
3. Pop-up 
4. When you click on the Cart in Peerfood, it shows the customer a quick preview down the bottom of the screen before proceeding to checkout.

Instead, little “+” sign should jump across screen and land in the cart like it does on Peerfood.

**Comment by softventure** [comment]
This cannot be a bug. It is a enhancement they are trying to fill in.
