### ISSUE TITLE
Pop up in food menu

### ISSUE THREAD

**Issue by BhavanaSJain** [softkoash-ashishjain/brunchery_v1#78]
![image](https://user-images.githubusercontent.com/8385702/44718707-8bd12000-aade-11e8-9fc1-3ff48988e85a.png)

**Comment by softventure** [comment]
@sawantsh Please take a look.

**Comment by softventure** [comment]
@BhavanaSJain Now this looks to be a duplicate of issue #121. Please clean up duplicate items, so we do not spend double efforts.
