### ISSUE TITLE
GUI issues in Partner With Us page

### ISSUE THREAD

**Issue by softkoash-ashishjain** [softkoash-ashishjain/brunchery_v1#9]
1. Icon is absent
2. Premier food photo upload option is missing.

Note: Is there any reason for separate fields for address added?

**Comment by BhavanaSJain** [comment]
Premier food have been decided to do later

**Comment by softventure** [comment]
Icon has been added.

**Comment by BhavanaSJain** [comment]
Premier food also we need to finish it off.

**Comment by BhavanaSJain** [comment]
Many lines we are not able to write. This is in app

**Comment by BhavanaSJain** [comment]
This issue is in my lg phone only.
